/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from "web3/eth/contract";
import { TransactionObject, BlockType } from "web3/eth/types";
import { Callback, EventLog } from "web3/types";
import { EventEmitter } from "events";
import { Provider } from "web3/providers";

export class ClaimableSplitCoin {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions);
  _address: string;
  options: contractOptions;
  methods: {
    splits(
      index: number | string
    ): TransactionObject<{
      to: string;
      ppm: string;
      0: string;
      1: string;
    }>;

    ownership(owner: string, index: number | string): TransactionObject<string>;

    getClaimableBalanceFor(user: string): TransactionObject<string>;

    claimFor(user: string): TransactionObject<void>;

    claim(): TransactionObject<void>;

    transfer(
      to: string,
      ppm: number | string,
      newOwner: string,
      toTransfer: string
    ): TransactionObject<void>;

    developer(): TransactionObject<string>;
    getSplitCount(): TransactionObject<string>;
    isClaimable(): TransactionObject<boolean>;
    getClaimableBalance(): TransactionObject<string>;
  };
  deploy(options: {
    data: string;
    arguments: any[];
  }): TransactionObject<Contract>;
  events: {
    SplitTransfer(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: string[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: string[];
      },
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
  getPastEvents(
    event: string,
    options?: {
      filter?: object;
      fromBlock?: BlockType;
      toBlock?: BlockType;
      topics?: string[];
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>;
  setProvider(provider: Provider): void;
}
