/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from "web3/eth/contract";
import { TransactionObject, BlockType } from "web3/eth/types";
import { Callback, EventLog } from "web3/types";
import { EventEmitter } from "events";
import { Provider } from "web3/providers";

export class MultiSigWallet {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions);
  _address: string;
  options: contractOptions;
  methods: {
    proposals(
      arg0: number | string
    ): TransactionObject<{
      to: string;
      amount: string;
      finalized: boolean;
      0: string;
      1: string;
      2: boolean;
    }>;

    signers(arg0: number | string): TransactionObject<string>;

    canSign(arg0: string): TransactionObject<boolean>;

    signerRequirementsMet(index: number | string): TransactionObject<boolean>;

    submitProposal(
      amount: number | string,
      to: string
    ): TransactionObject<void>;

    sign(proposalIndex: number | string): TransactionObject<void>;

    finalizeProposal(index: number | string): TransactionObject<void>;

    balance(): TransactionObject<string>;
  };
  deploy(options: {
    data: string;
    arguments: any[];
  }): TransactionObject<Contract>;
  events: {
    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: string[];
      },
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
  getPastEvents(
    event: string,
    options?: {
      filter?: object;
      fromBlock?: BlockType;
      toBlock?: BlockType;
      topics?: string[];
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>;
  setProvider(provider: Provider): void;
}
