/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from "web3/eth/contract";
import { TransactionObject, BlockType } from "web3/eth/types";
import { Callback, EventLog } from "web3/types";
import { EventEmitter } from "events";
import { Provider } from "web3/providers";

export class TaskRunner {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions);
  _address: string;
  options: contractOptions;
  methods: {
    canRun(index: number | string): TransactionObject<boolean>;

    taskAt(
      index: number | string
    ): TransactionObject<{
      0: string;
      1: string;
      2: (string)[];
      3: string;
      4: string;
    }>;

    addTask(
      fn: string | number[],
      location: string,
      params: (string | number[])[],
      repeatTimes: number | string,
      waitTime: number | string,
      incentive: number | string,
      billableWallet: string
    ): TransactionObject<void>;

    updateTask(
      contractLocation: string,
      repeatTimes: number | string,
      waitTime: number | string,
      incentive: number | string,
      billableWallet: string
    ): TransactionObject<void>;

    run(index: number | string): TransactionObject<void>;
  };
  deploy(options: {
    data: string;
    arguments: any[];
  }): TransactionObject<Contract>;
  events: {
    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: string[];
      },
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
  getPastEvents(
    event: string,
    options?: {
      filter?: object;
      fromBlock?: BlockType;
      toBlock?: BlockType;
      topics?: string[];
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>;
  setProvider(provider: Provider): void;
}
